# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

dist: trusty

php:
  - 5.6

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
        - CORE_RELEASE=3.3
    - php: 7.0
      env:
        - DB=MYSQL
        - CORE_RELEASE=3
    - php: 7.1
      env:
        - DB=MYSQL
        - PHPSTAN_TEST=1
        - CORE_RELEASE=3

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - if [[ -z $PHPSTAN_TEST ]]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi
  - if [[ $PHPSTAN_TEST ]]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require phpstan/phpstan-shim:0.9.2; fi
  - cd ~/builds/ss

script:
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR2 oldman/src/ oldman/tests/ -n; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan.phar analyse oldman/src -c "oldman/phpstan.neon" -a "oldman/tests/bootstrap-phpstan.php" --level 3; fi
  - vendor/bin/phpunit oldman/tests/
